version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
    # Add host.docker.internal to /etc/hosts to allow container to access host
    extra_hosts:
      - "host.docker.internal:host-gateway"
