version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../mlops:/app/mlops
      - ../model:/app/model
      - ../data:/app/data
      - api-cache:/app/cache
      - mlflow-data:/app/mlops/mlruns
    environment:
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=http://localhost:5173,http://localhost:8080
      - MLFLOW_TRACKING_URI=sqlite:///mlops/mlruns.db
      - MLFLOW_EXPERIMENT_NAME=fake-news-detector
    restart: unless-stopped
    networks:
      - fake-news-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow/mlruns
      - mlflow-artifacts:/mlflow/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts
    networks:
      - fake-news-network
    depends_on:
      - api

volumes:
  api-cache:
  mlflow-data:
  mlflow-artifacts:

networks:
  fake-news-network:
    driver: bridge
